<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-11T02:01:29 IST" name="SauceDemo_LoginPage_Validation_Suite" finished-at="2025-07-11T02:01:38 IST" duration-ms="8162">
    <groups>
      <group name="HardAssert">
        <method signature="SauceDemo_LoginPage_Validation.testCase3()[pri:-1, instance:org.page.saucedemo.SauceDemo_LoginPage_Validation@776aec5c]" name="testCase3" class="org.page.saucedemo.SauceDemo_LoginPage_Validation"/>
        <method signature="SauceDemo_LoginPage_Validation.testCase2()[pri:0, instance:org.page.saucedemo.SauceDemo_LoginPage_Validation@776aec5c]" name="testCase2" class="org.page.saucedemo.SauceDemo_LoginPage_Validation"/>
        <method signature="SauceDemo_LoginPage_Validation.testCase1()[pri:1, instance:org.page.saucedemo.SauceDemo_LoginPage_Validation@776aec5c]" name="testCase1" class="org.page.saucedemo.SauceDemo_LoginPage_Validation"/>
      </group> <!-- HardAssert -->
      <group name="SoftAssert">
        <method signature="SauceDemo_LoginPage_Validation.testCase4()[pri:5, instance:org.page.saucedemo.SauceDemo_LoginPage_Validation@776aec5c]" name="testCase4" class="org.page.saucedemo.SauceDemo_LoginPage_Validation"/>
      </group> <!-- SoftAssert -->
    </groups>
    <test started-at="2025-07-11T02:01:29 IST" name="SauceDemo_LoginPage_Validation_Test" finished-at="2025-07-11T02:01:38 IST" duration-ms="8162">
      <class name="org.page.saucedemo.SauceDemo_LoginPage_Validation">
        <test-method signature="testCase3()[pri:-1, instance:org.page.saucedemo.SauceDemo_LoginPage_Validation@776aec5c]" started-at="2025-07-11T02:01:29 IST" name="testCase3" finished-at="2025-07-11T02:01:33 IST" duration-ms="3392" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase3 -->
        <test-method signature="testCase2()[pri:0, instance:org.page.saucedemo.SauceDemo_LoginPage_Validation@776aec5c]" started-at="2025-07-11T02:01:33 IST" name="testCase2" finished-at="2025-07-11T02:01:34 IST" duration-ms="1448" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2 -->
        <test-method signature="testCase1()[pri:1, instance:org.page.saucedemo.SauceDemo_LoginPage_Validation@776aec5c]" started-at="2025-07-11T02:01:34 IST" name="testCase1" finished-at="2025-07-11T02:01:36 IST" duration-ms="1914" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase1 -->
        <test-method signature="testCase4()[pri:5, instance:org.page.saucedemo.SauceDemo_LoginPage_Validation@776aec5c]" started-at="2025-07-11T02:01:36 IST" name="testCase4" finished-at="2025-07-11T02:01:38 IST" duration-ms="1368" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at org.page.saucedemo.SauceDemo_LoginPage_Validation.testCase4(SauceDemo_LoginPage_Validation.java:95)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase4 -->
      </class> <!-- org.page.saucedemo.SauceDemo_LoginPage_Validation -->
    </test> <!-- SauceDemo_LoginPage_Validation_Test -->
  </suite> <!-- SauceDemo_LoginPage_Validation_Suite -->
</testng-results>
